import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Roboto } from 'next/font/google';
import './globals.css';
import classContainer from '../styles/contaner.module.scss';

const roboto = Roboto({ weight: '400', subsets: ['cyrillic'], style: 'normal' });

// export const metadata: Metadata = {
//   title: 'Main blog page | Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        <main>
          <div className={classContainer.container}>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
